### ISSUE TITLE
Research Git Rebase

### ISSUE THREAD

**Issue by nnh53** [PiedTeam/DreameCloneTraining-BE-Project#10]
- Approval Standards
  - Know how to use git rebase
  - Try to implement in some test repo

**Comment by lcaohoanq** [comment]
I've found this document, hope this be useful!

[001 Git-Github-Rebasing.pdf](https://github.com/PiedTeam/DreameCloneTraining-BE-Project/files/14878559/001.Git-Github-Rebasing.pdf)

**Comment by lcaohoanq** [comment]
My implement in here

> https://github.com/PiedTweet/Demo-Git

**Comment by lcaohoanq** [comment]
im done, need turn to review
@nnh53
