### ISSUE TITLE
BE04: Deploy & make "/upload" API

### ISSUE THREAD

**Issue by nnh53** [PiedTeam/DreameCloneTraining-BE-Project#53]
- Need: PiedTeam/DreameCloneTraining-FE-Project#7
- Related: 
- Approval Standards:
- Reason for the estimated point:
- Solution:

- [x] Render
- [x] Read file being send by FE
- [x] FE confirm correct file

**Comment by lcaohoanq** [comment]
@nnh53 
- Render: is this https://dashboard.render.com/
   -  What did i do with this website
- Read file being send by FE: 
   - Does this FE task done, if not do i need to simulator the whole process (i dont think so...)
- FE confirm correct file

**Comment by nnh53** [comment]
@l@lcaohoanq Deploy with render. Make route than use postman to send file to that domain

**Comment by lcaohoanq** [comment]
Render: https://dreameclonetraining-be.onrender.com/file/upload
method: post
form-data: 
- key: myFile
- value: <file>



![Image](https://github.com/PiedTeam/DreameCloneTraining-BE-Project/assets/136492579/dcd19b82-8e6e-4bc2-a689-545235bdfdb6)

**Comment by nnh53** [comment]
Make [ ] PiedTeam/DreameCloneTraining-FE-Project#33 because FE dont know how to replicate postman form-data

**Comment by nnh53** [comment]
@lcaohoanq 
Cannot handle utf vietnamese file name

![Image](https://github.com/PiedTeam/DreameCloneTraining-BE-Project/assets/113448161/7a87b145-acb9-4c9a-9427-06bc7c355fb0)



![Image](https://github.com/PiedTeam/DreameCloneTraining-BE-Project/assets/113448161/64e46b9b-e16f-4e3f-9cfd-546e849142af)

**Comment by lcaohoanq** [comment]
> @lcaohoanq Cannot handle unicode vietnamese file name #63
> 
> ![Image](https://private-user-images.githubusercontent.com/113448161/327731568-7a87b145-acb9-4c9a-9427-06bc7c355fb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NDE2MDMsIm5iZiI6MTcxNDc0MTMwMywicGF0aCI6Ii8xMTM0NDgxNjEvMzI3NzMxNTY4LTdhODdiMTQ1LWFjYjktNGM5YS05NDI3LTA2YmM3YzM1NWZiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QxMzAxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTgxOTAyOWRhZmNlNWU2YTQxYjM0NzA2MjBjNjMyMThjZWZiNTZjNGVmNTJmZTM4YjEyNDRhNmYxMTI0ZDQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DVAUBLofjQTiiMJ8FsWmmhBAWkjnIReIAKQuFQPZGDA)
> 
> ![Image](https://private-user-images.githubusercontent.com/113448161/327731651-64e46b9b-e16f-4e3f-9cfd-546e849142af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NDE2MDMsIm5iZiI6MTcxNDc0MTMwMywicGF0aCI6Ii8xMTM0NDgxNjEvMzI3NzMxNjUxLTY0ZTQ2YjliLWUxNmYtNGUzZi05Y2ZkLTU0NmU4NDkxNDJhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QxMzAxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjZmMTRhMDhlZGQ5NjlmODdkMzcxNzQwNmE5NzU1ZTg5MWNlNjg4MDM4MmM0NDQ4NDlhM2Q0MmRlYmYyNzZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vMBYYiydiGKeH7pXM4AnSdxYlNN2WFJuX1F4g0jdhkU)

Yes, i see, did i forgot something? This task is base on #2, and i've read the requirement that only mentioned about English file name
![image](https://github.com/PiedTeam/DreameCloneTraining-BE-Project/assets/136492579/242eac6e-e5c0-4610-934d-d243b7724093)
