### ISSUE TITLE
BE02: Compare the title of column with the properties of product in system

### ISSUE THREAD

**Issue by nnh53** [PiedTeam/DreameCloneTraining-BE-Project#6]
(US-03)
- Description:
  - This happen when user want to add new or update 
  - Get the title collum from the inputted file, compare
  - If not enough column provided, throw error
  - The demo file can include:
     - id
     - name
> for test only
- Reason for the estimated point:
   - Have experience, but need research in new language
- Approval Standards:
  - Response the error message 
  - Enough columns base on the current file

**Comment by nnh53** [comment]
![Image](https://github.com/PiedTeam/DreameCloneTraining-BE-Project/assets/113448161/58aa5585-b318-435e-9414-cd682ae9f960)

**Comment by nnh53** [comment]
TestCase need to think 

![Image](https://github.com/PiedTeam/DreameCloneTraining-BE-Project/assets/113448161/55e6b92f-d5d0-4b48-96c0-2d47cb4b6c7e)



![Image](https://github.com/PiedTeam/DreameCloneTraining-BE-Project/assets/113448161/328ad188-e21a-40a3-bbf3-c056376b3017)

**Comment by lcaohoanq** [comment]
@nnh53 
> If not enough column provided, throw error
- Tạo thử một Type (khuôn gốc): demo bằng id,name, type để check

**Comment by nnh53** [comment]
- use exclude and extract in typescript

**Comment by nnh53** [comment]
- Move to sprint 3

**Comment by lcaohoanq** [comment]
@nnh53 already done code in #2
