### ISSUE TITLE
Create Backend Structure

### ISSUE THREAD

**Issue by nnh53** [PiedTeam/DreameCloneTraining-BE-Project#9]
![Image](https://github.com/PiedTeam/DreameCloneTraining-BE-Project/assets/108606108/8ad029a5-2f12-404c-b7e7-dce37c3ab649)

**Comment by huy1707developer** [comment]
About yarn.lock:
https://classic.yarnpkg.com/blog/2017/05/31/determinism/
https://stackoverflow.com/questions/44897368/what-is-the-difference-between-yarn-lock-and-npms-package-lock
